version: '3.1'
services:
  mysql:
    image: mysql:8.0.22
    platform: linux/amd64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: visitorstatistics
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: visitorstatistics
      TZ: Asia/Seoul